In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [6]:
df = pd.read_csv('homeprices2.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
df.isnull().values.any()

True

In [9]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

### Fill NA values with median value of a column

In [10]:
df.bedrooms.median()

4.0

In [11]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [14]:
X=df.drop('price',axis='columns')
y=df.price

In [16]:
reg = linear_model.LinearRegression()
reg.fit(X,y)

LinearRegression()

In [18]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [19]:
reg.intercept_

221323.00186540408

### Predict price of home with 3000 sqr ft area, 3 bedrooms, 40 year old

In [20]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [21]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

498408.25157402386

### Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old 

In [22]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])